import { Project } from './Item';

export const projects: Project[] = [
  {
    id: 1,
    name: 'Ballycullen',
    showOnHome: true,
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 2,
    name: 'Blessington No.1',
    showOnHome: true,
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 3,
    name: '???',
    showOnHome: true,
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 4,
    name: 'Project 1',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 5,
    name: 'Project 1',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },

  {
    id: 6,
    name: 'Project 1',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 7,
    name: 'Project 1',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 8,
    name: 'Project 1',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 9,
    name: 'Project 1 home',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 10,
    name: 'Project 1',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 11,
    name: 'Project 3 Featured 3',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
  {
    id: 12,
    name: 'Project 1 home',
    logo: 'logo',
    tags: ['tag1', 'tag2'],
    thumbnail: 'marina-zvada-i-rflWX15kg-unsplash',
    description: 'This is a description of the project.',
  },
];
